# Revolution

------------------------------------------------------------------------

  Revolution is classified as a shedding-type card game. The name of the game is to play all of your cards and be the first one out. The order in which you go out corresponds to your rank in the next game. Each rank may carry a special set of benefits (or consequences) that are enacted at the start of each game.

## Setup

------------------------------------------------------------------------

- Remove Joker cards (unless playing with ultimate rules)
- 4-5 players use one singular deck of cards
- 6-9 players use two decks of cards
- 10-12 players use three decks of cards

## General Rules

------------------------------------------------------------------------

### Basic Rules

1.  At the start of the determinant (first) round, the player to the left of the dealer lays the opening card. In all rounds proceeding the determinant round, the **King** lays the opening card.

2.  Every card played ***must*** equal or exceed the value of the previous card (suit is obsolete).

3.  Cards may be laid in pairs, triples, quadruples, etc as long as the previous card is of the same quantity. The quantity of the cards stays static until the deck is cleared.

    > *E.g. Double fives are played, anything equal to or above double fives may be played (a single five would not be allowed).*

4.  The number 2 card acts as a sort of wild. It may be used to ***clear*** the deck (all cards laid are discarded) during your turn allowing you to play any card(s) of any quantity of your choice.

5.  Playing a card of the same value on the previous card results in the next player being skipped.

6.  After a player goes out, the deck is ***cleared*** and the next player begins their turn.

### Ultimate Rules (Optional)

5.  Any card / card combinations able to be wholly divided may be played as their divisible numbers. After the turn, the cards played must remain in that quantity unless again *switched* (value remains the same while the card quantity changes).

    > *E.g. A queen is played (equal to 12). 4 threes may be played; 3 fours may be played; 2 sixes may be played; 1 queen may be played (only the exact same card skips the next player's turn). Since these cards are all equal to 12, any of these can be played on any of these combinations at any point.*
    >
    > E.g. 3 fours are played (equal to 12). 4 threes may be played; 3 fours may be played (only the exact same card skips the next player's turn); 2 sixes may be played; 1 queen may be played.

6.  Joker cards are reintroduced as reverse cards (reminiscent to Uno reverse cards).

### Card Values

------------------------------------------------------------------------

- Two is valued the highest
- Ace is equal to 14
- King is equal to 13
- Queen is equal to 12
- Jack is equal to 11
- Jokers reverse the playing direction **(optional)**

### Player Ranks

------------------------------------------------------------------------

  After the determinant round is concluded, depending on when you went out (played your last card), ranks will be given to each player in order of first-last to go out. The ranks go as follows:

1.  **King** (4-10 players)\
    *Has the option to take the two best cards from the dung, must give two cards in return (the dung may request specific cards).*

2.  **Queen** (4-10 players)\
    *Has the option to take the singular best card from the serf, must give one card in return (the serf may request a specific card).*

3.  **Prince** (5-10 players)\
    *Has the option to force the Thane to swap his whole hand with the Prince.*

4.  **Duke** (9-10 players)\
    *Has the option to force the Squire into a blind card exchange.*

5.  **Baron** (7-10 players)*\
    Has the option to initiate a single card trade with the Knight.*

6.  **Knight** (8-10 players)*\
    Can decline the single card trade with the Baron.*

7.  **Squire** (10 players)\
    *Must comply with the Duke if he forces a blind card exchange.*

8.  **Thane** (6-10 players)\
    *Must comply with the Prince if he forces to swap hands.*

9.  **Serf** (4-10 players)\
    *Must comply with the Queen if she taxes the serf for his singular best card.*

10. **Dung** (4-10 players)\
    *Must comply with the King if he taxes the dung for his two bests cards.*

## How to Play

------------------------------------------------------------------------

### Determinant Round

  Begin by dealing an equal amount of hands to players, deal all the cards in the deck(s) until the deck(s) are gone. In the determinant round, the hands are dealt to players at random. The first player to the left of the dealer will begin the round by placing a card (typically a low card). Continue the game consulting the rules when needed. Keep track of who goes out in what order, this will be important for the proceeding rounds.

### Proceeding Rounds

  Begin by dealing an equal amount of hands to players, deal all the cards in the deck(s) until the deck(s) are gone. In the proceeding rounds, each player is given a rank based on when that player finish their deck. The first player to go out is awarded the position of **King** and so on. These ranks are also the order in which each player picks their decks (**King** first, **Dung** last). The players will then use their rank abilities before the round starts to gain an edge in game (or not depending on your rank). The round will then begin with the **King** laying the opening card. The proceeding rounds will follow the same formula with players ranks shuffling the longer you play.
